In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('C:/Users/Kashmira Lokhande/Desktop/VMWARE.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
X

array([[  1. ,   3.5,   0. , 200. ,  75. ,   0. ,   0. ,   0.5,   0. ],
       [  1. ,   3.5,   0. , 200. ,  75. ,   0. ,   0. ,   0.5,   0. ],
       [  0. ,   5. ,   0. , 200. ,  50. ,   0. ,   0. ,   0. ,   0.5],
       [  0. ,   4.6,   0. , 100. ,  50. ,   0. ,   0.5,   0.5,   0.5],
       [  2. ,   4.3,   0. , 200. ,  75. ,   0. ,   0. ,   0. ,   0.5],
       [  3. ,   5. ,   0. , 200. ,  50. ,   0. ,   0. ,   0.5,   0. ],
       [  4. ,   4.3,   0. , 200. ,  75. ,   0. ,   0. ,   0.5,   0. ],
       [  0. ,   9. ,   0. , 200. ,  50. ,   0. ,   1. ,   1. ,   1. ],
       [  0. ,   4.3,   0. , 200. ,  75. ,   0. ,   0.5,   0. ,   0. ],
       [  0. ,   4. ,   0. , 200. ,  50. ,   0. ,   0. ,   0.5,   0. ],
       [  0. ,   5. ,   0. , 200. ,  50. ,   0. ,   0.5,   0. ,   0. ],
       [  0. ,   4. ,   0. , 200. ,  50. ,   0. ,   0.5,   0. ,   0. ],
       [  2. ,   5. ,   0. , 200. ,  50. ,   0. ,   0. ,   0. ,   0.5],
       [  0. ,   5. ,   0. , 200. ,  50. ,   0. ,   0.5,   0. , 

In [4]:
y

array([1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0], dtype=int64)

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [6]:
print(X_train)

[[  4.    5.    0.  200.   50.    0.    0.5   0.    0. ]
 [  3.    4.    0.  200.   50.    0.    0.5   0.    0. ]
 [  0.    9.    0.  200.   50.    0.    1.    1.    1. ]
 [  0.    5.    0.  200.   50.    0.    0.5   0.    0. ]
 [  0.    4.6   0.  100.   50.    0.    0.5   0.5   0.5]
 [  0.    2.1   0.  100.   50.    0.    0.5   0.    0. ]
 [  0.    5.    0.  200.   50.    0.    0.    0.5   0. ]
 [  0.    5.    0.  200.   50.    0.    0.    0.5   0. ]
 [  5.    5.    0.  200.   50.    0.    0.    0.    0.5]
 [  0.    5.    0.  200.   50.    0.    0.5   0.    0. ]
 [  0.    5.    0.  200.   50.    0.    0.5   0.    0. ]
 [  4.    6.8   0.  200.   75.    0.    0.5   0.5   0.5]
 [  0.    2.1   0.  100.   50.    0.    0.    0.    0.5]
 [  0.    4.    0.  200.   50.    0.    0.5   0.    0. ]
 [  0.    4.3   0.  200.   75.    0.    0.5   0.    0. ]
 [  0.    5.    0.  200.   50.    0.    0.5   0.    0. ]
 [  0.    7.2   0.  100.   50.    0.    1.    1.    1. ]
 [  3.    5.    0.  200.   50. 

In [7]:
print(y_train)

[1 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 1 1 0 1 1 1 0 1 0 0 1 0 0 1 0 0]


In [8]:
print(X_test)

[[  0.    5.    0.  200.   50.    0.    0.5   0.    0. ]
 [  0.    4.    0.  200.   50.    0.    0.5   0.    0. ]
 [  0.    5.    0.  200.   50.    0.    0.5   0.    0. ]
 [  0.    5.    0.  200.   50.    0.    0.    0.    0.5]
 [  0.    5.    0.  200.   50.    0.    0.    0.    0.5]
 [  3.    5.    0.  200.   50.    0.    0.5   0.    0. ]
 [  0.    6.9   0.  100.   75.    0.    1.    1.    1. ]
 [  5.    5.    0.  200.   50.    0.    0.    0.    0.5]
 [  0.    6.4   0.  200.   50.    0.    0.    0.5   0.5]
 [  2.    4.3   0.  200.   75.    0.    0.    0.    0.5]
 [  0.    2.1   0.  100.   50.    0.    0.5   0.    0. ]
 [  1.    7.5   0.  200.   50.    0.    0.5   0.5   0.5]
 [  1.    9.    0.  200.   50.    0.    1.    1.    1. ]]


In [9]:
print(y_test)

[0 0 0 0 0 0 0 1 0 1 0 1 1]


In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train)

[[ 1.20614902  0.07194671  0.          0.52522573 -0.52522573  0.
   0.52522573 -0.93638218 -0.71262682]
 [ 0.72106735 -0.56186958  0.          0.52522573 -0.52522573  0.
   0.52522573 -0.93638218 -0.71262682]
 [-0.73417767  2.60721189  0.          0.52522573 -0.52522573  0.
   2.14467174  2.21326698  2.21706123]
 [-0.73417767  0.07194671  0.          0.52522573 -0.52522573  0.
   0.52522573 -0.93638218 -0.71262682]
 [-0.73417767 -0.1815798   0.         -1.90394328 -0.52522573  0.
   0.52522573  0.6384424   0.7522172 ]
 [-0.73417767 -1.76612054  0.         -1.90394328 -0.52522573  0.
   0.52522573 -0.93638218 -0.71262682]
 [-0.73417767  0.07194671  0.          0.52522573 -0.52522573  0.
  -1.09422027  0.6384424  -0.71262682]
 [-0.73417767  0.07194671  0.          0.52522573 -0.52522573  0.
  -1.09422027  0.6384424  -0.71262682]
 [ 1.69123069  0.07194671  0.          0.52522573 -0.52522573  0.
  -1.09422027 -0.93638218  0.7522172 ]
 [-0.73417767  0.07194671  0.          0.52522573 -0.52

In [12]:
print(X_test)

[[-0.73417767  0.07194671  0.          0.52522573 -0.52522573  0.
   0.52522573 -0.93638218 -0.71262682]
 [-0.73417767 -0.56186958  0.          0.52522573 -0.52522573  0.
   0.52522573 -0.93638218 -0.71262682]
 [-0.73417767  0.07194671  0.          0.52522573 -0.52522573  0.
   0.52522573 -0.93638218 -0.71262682]
 [-0.73417767  0.07194671  0.          0.52522573 -0.52522573  0.
  -1.09422027 -0.93638218  0.7522172 ]
 [-0.73417767  0.07194671  0.          0.52522573 -0.52522573  0.
  -1.09422027 -0.93638218  0.7522172 ]
 [ 0.72106735  0.07194671  0.          0.52522573 -0.52522573  0.
   0.52522573 -0.93638218 -0.71262682]
 [-0.73417767  1.27619767  0.         -1.90394328  1.90394328  0.
   2.14467174  2.21326698  2.21706123]
 [ 1.69123069  0.07194671  0.          0.52522573 -0.52522573  0.
  -1.09422027 -0.93638218  0.7522172 ]
 [-0.73417767  0.95928953  0.          0.52522573 -0.52522573  0.
  -1.09422027  0.6384424   0.7522172 ]
 [ 0.23598568 -0.37172469  0.          0.52522573  1.90

In [13]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [14]:
print(classifier.predict(sc.transform([[2,2.1,0,100,50,0,0.5,0,0]])))

[0]


In [15]:

print(classifier.predict(sc.transform([[1,4.6,0,100,50,0,0.5,0.5,0.5]])))

[0]


In [16]:

print(classifier.predict(sc.transform([[0,4.4,0,100,75,0,0.5,0.5,0.5]])))

[0]


In [17]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 1]
 [0 1]]


In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[8 1]
 [2 2]]


0.7692307692307693